#!/bin/sh
echo "a4"
 node a4
echo "english"
 node english
echo "euro"
 node euro
echo "french"
 node french
echo "italian"
 node italian
echo "multipage"
 node multipage
echo "no-amount"
 node no-amount
echo "no-debitor"
 node no-debitor
echo "no-debitor-no-amount"
 node no-debitor-no-amount
echo "no-debitor-no-amount-no-reference"
 node no-debitor-no-amount-no-reference
echo "no-debitor-no-reference"
 node no-debitor-no-reference
echo "normal-iban"
 node normal-iban
echo "separate"
 node separate
echo "ts"
tsc ts.ts
 node ts
 rm ts.js